package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/spf13/cobra"
)

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Interactive setup wizard for distributed storage node",
	RunE: func(cmd *cobra.Command, args []string) error {
		configPath := "oelala-storage.yaml"
		if cfgFile != "" {
			configPath = cfgFile
		}

		fmt.Println("🚀 Welcome to the oelala-storage node setup wizard!")
		fmt.Println("This will configure your node to connect to the Coordinator.")
		fmt.Println()

		reader := bufio.NewReader(os.Stdin)

		// Helper function for prompting
		prompt := func(label, defaultVal string) string {
			if defaultVal != "" {
				fmt.Printf("%s [%s]: ", label, defaultVal)
			} else {
				fmt.Printf("%s: ", label)
			}

			input, err := reader.ReadString('\n')
			if err != nil {
				return defaultVal
			}
			input = strings.TrimSpace(input)
			if input == "" {
				return defaultVal
			}
			return input
		}

		// 1. Storage Path
		storagePath := prompt("📦 Storage path", "./data")
		storagePath, _ = filepath.Abs(storagePath)

		// 2. Max Storage
		maxStorageStr := prompt("💾 Max storage limit in GB", "500")
		maxStorage, err := strconv.Atoi(maxStorageStr)
		if err != nil || maxStorage <= 0 {
			fmt.Println("⚠️ Invalid storage size, defaulting to 500GB")
			maxStorage = 500
		}

		// 3. Coordinator URL
		coordinatorURL := prompt("🌐 Coordinator URL", "https://api.oelala.xyz")

		// 4. API Key
		apiKey := prompt("🔑 Node API Key", "")
		if apiKey == "" {
			fmt.Println("⚠️ Warning: No API key provided. Your node won't be able to authenticate with the coordinator.")
		}

		fmt.Println()
		fmt.Println("Generating configuration...")

		// Generate the config file content
		configContent := fmt.Sprintf(`# oelala-storage configuration (generated by setup wizard)
node:
  id: "auto"
  name: "My Storage Node"
  type: primary

storage:
  path: "%s"
  max_size_gb: %d
  cache_size_mb: 2048

api:
  http_port: 7990
  grpc_port: 7991
  enable_tls: false

sync:
  enabled: true
  peers: []
  strategy: realtime
  interval_minutes: 15

coordinator:
  enabled: true
  url: "%s"
  api_key: "%s"
  heartbeat_secs: 60

security:
  encryption_at_rest: false
  auth_tokens:
    - name: "default"
      token: ""
      permissions: ["read", "write", "delete"]
`, storagePath, maxStorage, coordinatorURL, apiKey)

		// Handle existing config warning
		if _, err := os.Stat(configPath); err == nil {
			fmt.Printf("⚠️ File %s already exists.\n", configPath)
			confirm := prompt("Overwrite? (y/n)", "n")
			if strings.ToLower(confirm) != "y" {
				fmt.Println("Setup aborted.")
				return nil
			}
		}

		if err := os.WriteFile(configPath, []byte(configContent), 0600); err != nil {
			return fmt.Errorf("failed to write config: %w", err)
		}

		fmt.Printf("✅ Success! Created config file at: %s\n", configPath)
		fmt.Println()
		fmt.Println("Next steps:")
		fmt.Println("1. Run your node: ./bin/oelala-storage serve")
		fmt.Println("2. Your node will automatically heartbeat to the coordinator!")

		return nil
	},
}

func init() {
	rootCmd.AddCommand(setupCmd)
}
