// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncState represents current sync status
type SyncState int32

const (
	SyncState_SYNC_STATE_UNKNOWN SyncState = 0
	SyncState_SYNC_STATE_IDLE    SyncState = 1
	SyncState_SYNC_STATE_SYNCING SyncState = 2
	SyncState_SYNC_STATE_ERROR   SyncState = 3
)

// Enum value maps for SyncState.
var (
	SyncState_name = map[int32]string{
		0: "SYNC_STATE_UNKNOWN",
		1: "SYNC_STATE_IDLE",
		2: "SYNC_STATE_SYNCING",
		3: "SYNC_STATE_ERROR",
	}
	SyncState_value = map[string]int32{
		"SYNC_STATE_UNKNOWN": 0,
		"SYNC_STATE_IDLE":    1,
		"SYNC_STATE_SYNCING": 2,
		"SYNC_STATE_ERROR":   3,
	}
)

func (x SyncState) Enum() *SyncState {
	p := new(SyncState)
	*p = x
	return p
}

func (x SyncState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_storage_proto_enumTypes[0].Descriptor()
}

func (SyncState) Type() protoreflect.EnumType {
	return &file_api_proto_storage_proto_enumTypes[0]
}

func (x SyncState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncState.Descriptor instead.
func (SyncState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{0}
}

// PeerInfo contains peer identification
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	StorageBytes  int64                  `protobuf:"varint,5,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	ObjectCount   int64                  `protobuf:"varint,6,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_api_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PeerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PeerInfo) GetStorageBytes() int64 {
	if x != nil {
		return x.StorageBytes
	}
	return 0
}

func (x *PeerInfo) GetObjectCount() int64 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

// HandshakeRequest initiates peer connection
type HandshakeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Peer              *PeerInfo              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	SupportedFeatures []string               `protobuf:"bytes,2,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_api_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *HandshakeRequest) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

// HandshakeResponse confirms peer connection
type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Peer            *PeerInfo              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Accepted        bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason    string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	EnabledFeatures []string               `protobuf:"bytes,4,rep,name=enabled_features,json=enabledFeatures,proto3" json:"enabled_features,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_api_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *HandshakeResponse) GetEnabledFeatures() []string {
	if x != nil {
		return x.EnabledFeatures
	}
	return nil
}

// ObjectMeta contains object metadata for sync
type ObjectMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"` // SHA-256
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	ModifiedAt    int64                  `protobuf:"varint,7,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	UserMetadata  map[string]string      `protobuf:"bytes,8,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_api_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectMeta) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ObjectMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectMeta) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ObjectMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectMeta) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ObjectMeta) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ObjectMeta) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *ObjectMeta) GetUserMetadata() map[string]string {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

// ListObjectsRequest queries objects for sync
type ListObjectsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Bucket         string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"` // Empty for all buckets
	Prefix         string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	SinceTimestamp int64                  `protobuf:"varint,3,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"` // Only objects modified after this time
	ExcludeHashes  []string               `protobuf:"bytes,4,rep,name=exclude_hashes,json=excludeHashes,proto3" json:"exclude_hashes,omitempty"`     // Hashes we already have
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_api_proto_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ListObjectsRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ListObjectsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListObjectsRequest) GetSinceTimestamp() int64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

func (x *ListObjectsRequest) GetExcludeHashes() []string {
	if x != nil {
		return x.ExcludeHashes
	}
	return nil
}

func (x *ListObjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListObjectsResponse returns objects available for sync
type ListObjectsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Objects           []*ObjectMeta          `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	HasMore           bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	ContinuationToken string                 `protobuf:"bytes,3,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_api_proto_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ListObjectsResponse) GetObjects() []*ObjectMeta {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListObjectsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListObjectsResponse) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

// GetObjectRequest requests object data
type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedHash  string                 `protobuf:"bytes,3,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"` // Verify we get the right version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_api_proto_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{6}
}

func (x *GetObjectRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetObjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetObjectRequest) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

// ObjectChunk streams object data
type ObjectChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ObjectChunk_Meta
	//	*ObjectChunk_Data
	Payload       isObjectChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectChunk) Reset() {
	*x = ObjectChunk{}
	mi := &file_api_proto_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectChunk) ProtoMessage() {}

func (x *ObjectChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectChunk.ProtoReflect.Descriptor instead.
func (*ObjectChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectChunk) GetPayload() isObjectChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ObjectChunk) GetMeta() *ObjectMeta {
	if x != nil {
		if x, ok := x.Payload.(*ObjectChunk_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *ObjectChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ObjectChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isObjectChunk_Payload interface {
	isObjectChunk_Payload()
}

type ObjectChunk_Meta struct {
	Meta *ObjectMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"` // First chunk contains metadata
}

type ObjectChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // Subsequent chunks contain data
}

func (*ObjectChunk_Meta) isObjectChunk_Payload() {}

func (*ObjectChunk_Data) isObjectChunk_Payload() {}

// PushObjectResponse confirms object received
type PushObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"` // Hash of received data
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushObjectResponse) Reset() {
	*x = PushObjectResponse{}
	mi := &file_api_proto_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushObjectResponse) ProtoMessage() {}

func (x *PushObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushObjectResponse.ProtoReflect.Descriptor instead.
func (*PushObjectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{8}
}

func (x *PushObjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushObjectResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PushObjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SyncStatusRequest queries sync state
type SyncStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStatusRequest) Reset() {
	*x = SyncStatusRequest{}
	mi := &file_api_proto_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatusRequest) ProtoMessage() {}

func (x *SyncStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatusRequest.ProtoReflect.Descriptor instead.
func (*SyncStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{9}
}

func (x *SyncStatusRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// SyncStatusResponse returns sync state
type SyncStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LastSyncTime   int64                  `protobuf:"varint,1,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	ObjectsSynced  int64                  `protobuf:"varint,2,opt,name=objects_synced,json=objectsSynced,proto3" json:"objects_synced,omitempty"`
	BytesSynced    int64                  `protobuf:"varint,3,opt,name=bytes_synced,json=bytesSynced,proto3" json:"bytes_synced,omitempty"`
	PendingObjects int64                  `protobuf:"varint,4,opt,name=pending_objects,json=pendingObjects,proto3" json:"pending_objects,omitempty"`
	State          SyncState              `protobuf:"varint,5,opt,name=state,proto3,enum=oelala.storage.v1.SyncState" json:"state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncStatusResponse) Reset() {
	*x = SyncStatusResponse{}
	mi := &file_api_proto_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatusResponse) ProtoMessage() {}

func (x *SyncStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatusResponse.ProtoReflect.Descriptor instead.
func (*SyncStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_storage_proto_rawDescGZIP(), []int{10}
}

func (x *SyncStatusResponse) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

func (x *SyncStatusResponse) GetObjectsSynced() int64 {
	if x != nil {
		return x.ObjectsSynced
	}
	return 0
}

func (x *SyncStatusResponse) GetBytesSynced() int64 {
	if x != nil {
		return x.BytesSynced
	}
	return 0
}

func (x *SyncStatusResponse) GetPendingObjects() int64 {
	if x != nil {
		return x.PendingObjects
	}
	return 0
}

func (x *SyncStatusResponse) GetState() SyncState {
	if x != nil {
		return x.State
	}
	return SyncState_SYNC_STATE_UNKNOWN
}

var File_api_proto_storage_proto protoreflect.FileDescriptor

const file_api_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/storage.proto\x12\x11oelala.storage.v1\"\xb3\x01\n" +
	"\bPeerInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12#\n" +
	"\rstorage_bytes\x18\x05 \x01(\x03R\fstorageBytes\x12!\n" +
	"\fobject_count\x18\x06 \x01(\x03R\vobjectCount\"r\n" +
	"\x10HandshakeRequest\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.oelala.storage.v1.PeerInfoR\x04peer\x12-\n" +
	"\x12supported_features\x18\x02 \x03(\tR\x11supportedFeatures\"\xb0\x01\n" +
	"\x11HandshakeResponse\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.oelala.storage.v1.PeerInfoR\x04peer\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\x12)\n" +
	"\x10enabled_features\x18\x04 \x03(\tR\x0fenabledFeatures\"\xd8\x02\n" +
	"\n" +
	"ObjectMeta\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vmodified_at\x18\a \x01(\x03R\n" +
	"modifiedAt\x12T\n" +
	"\ruser_metadata\x18\b \x03(\v2/.oelala.storage.v1.ObjectMeta.UserMetadataEntryR\fuserMetadata\x1a?\n" +
	"\x11UserMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\x12ListObjectsRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12'\n" +
	"\x0fsince_timestamp\x18\x03 \x01(\x03R\x0esinceTimestamp\x12%\n" +
	"\x0eexclude_hashes\x18\x04 \x03(\tR\rexcludeHashes\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x98\x01\n" +
	"\x13ListObjectsResponse\x127\n" +
	"\aobjects\x18\x01 \x03(\v2\x1d.oelala.storage.v1.ObjectMetaR\aobjects\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12-\n" +
	"\x12continuation_token\x18\x03 \x01(\tR\x11continuationToken\"a\n" +
	"\x10GetObjectRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12#\n" +
	"\rexpected_hash\x18\x03 \x01(\tR\fexpectedHash\"c\n" +
	"\vObjectChunk\x123\n" +
	"\x04meta\x18\x01 \x01(\v2\x1d.oelala.storage.v1.ObjectMetaH\x00R\x04meta\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"X\n" +
	"\x12PushObjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\",\n" +
	"\x11SyncStatusRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"\xe1\x01\n" +
	"\x12SyncStatusResponse\x12$\n" +
	"\x0elast_sync_time\x18\x01 \x01(\x03R\flastSyncTime\x12%\n" +
	"\x0eobjects_synced\x18\x02 \x01(\x03R\robjectsSynced\x12!\n" +
	"\fbytes_synced\x18\x03 \x01(\x03R\vbytesSynced\x12'\n" +
	"\x0fpending_objects\x18\x04 \x01(\x03R\x0ependingObjects\x122\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1c.oelala.storage.v1.SyncStateR\x05state*f\n" +
	"\tSyncState\x12\x16\n" +
	"\x12SYNC_STATE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSYNC_STATE_IDLE\x10\x01\x12\x16\n" +
	"\x12SYNC_STATE_SYNCING\x10\x02\x12\x14\n" +
	"\x10SYNC_STATE_ERROR\x10\x032\xc9\x03\n" +
	"\vSyncService\x12V\n" +
	"\tHandshake\x12#.oelala.storage.v1.HandshakeRequest\x1a$.oelala.storage.v1.HandshakeResponse\x12\\\n" +
	"\vListObjects\x12%.oelala.storage.v1.ListObjectsRequest\x1a&.oelala.storage.v1.ListObjectsResponse\x12R\n" +
	"\tGetObject\x12#.oelala.storage.v1.GetObjectRequest\x1a\x1e.oelala.storage.v1.ObjectChunk0\x01\x12U\n" +
	"\n" +
	"PushObject\x12\x1e.oelala.storage.v1.ObjectChunk\x1a%.oelala.storage.v1.PushObjectResponse(\x01\x12Y\n" +
	"\n" +
	"SyncStatus\x12$.oelala.storage.v1.SyncStatusRequest\x1a%.oelala.storage.v1.SyncStatusResponseB8Z6github.com/m0nklabs/oelala-storage/api/proto/storagepbb\x06proto3"

var (
	file_api_proto_storage_proto_rawDescOnce sync.Once
	file_api_proto_storage_proto_rawDescData []byte
)

func file_api_proto_storage_proto_rawDescGZIP() []byte {
	file_api_proto_storage_proto_rawDescOnce.Do(func() {
		file_api_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_storage_proto_rawDesc), len(file_api_proto_storage_proto_rawDesc)))
	})
	return file_api_proto_storage_proto_rawDescData
}

var file_api_proto_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_storage_proto_goTypes = []any{
	(SyncState)(0),              // 0: oelala.storage.v1.SyncState
	(*PeerInfo)(nil),            // 1: oelala.storage.v1.PeerInfo
	(*HandshakeRequest)(nil),    // 2: oelala.storage.v1.HandshakeRequest
	(*HandshakeResponse)(nil),   // 3: oelala.storage.v1.HandshakeResponse
	(*ObjectMeta)(nil),          // 4: oelala.storage.v1.ObjectMeta
	(*ListObjectsRequest)(nil),  // 5: oelala.storage.v1.ListObjectsRequest
	(*ListObjectsResponse)(nil), // 6: oelala.storage.v1.ListObjectsResponse
	(*GetObjectRequest)(nil),    // 7: oelala.storage.v1.GetObjectRequest
	(*ObjectChunk)(nil),         // 8: oelala.storage.v1.ObjectChunk
	(*PushObjectResponse)(nil),  // 9: oelala.storage.v1.PushObjectResponse
	(*SyncStatusRequest)(nil),   // 10: oelala.storage.v1.SyncStatusRequest
	(*SyncStatusResponse)(nil),  // 11: oelala.storage.v1.SyncStatusResponse
	nil,                         // 12: oelala.storage.v1.ObjectMeta.UserMetadataEntry
}
var file_api_proto_storage_proto_depIdxs = []int32{
	1,  // 0: oelala.storage.v1.HandshakeRequest.peer:type_name -> oelala.storage.v1.PeerInfo
	1,  // 1: oelala.storage.v1.HandshakeResponse.peer:type_name -> oelala.storage.v1.PeerInfo
	12, // 2: oelala.storage.v1.ObjectMeta.user_metadata:type_name -> oelala.storage.v1.ObjectMeta.UserMetadataEntry
	4,  // 3: oelala.storage.v1.ListObjectsResponse.objects:type_name -> oelala.storage.v1.ObjectMeta
	4,  // 4: oelala.storage.v1.ObjectChunk.meta:type_name -> oelala.storage.v1.ObjectMeta
	0,  // 5: oelala.storage.v1.SyncStatusResponse.state:type_name -> oelala.storage.v1.SyncState
	2,  // 6: oelala.storage.v1.SyncService.Handshake:input_type -> oelala.storage.v1.HandshakeRequest
	5,  // 7: oelala.storage.v1.SyncService.ListObjects:input_type -> oelala.storage.v1.ListObjectsRequest
	7,  // 8: oelala.storage.v1.SyncService.GetObject:input_type -> oelala.storage.v1.GetObjectRequest
	8,  // 9: oelala.storage.v1.SyncService.PushObject:input_type -> oelala.storage.v1.ObjectChunk
	10, // 10: oelala.storage.v1.SyncService.SyncStatus:input_type -> oelala.storage.v1.SyncStatusRequest
	3,  // 11: oelala.storage.v1.SyncService.Handshake:output_type -> oelala.storage.v1.HandshakeResponse
	6,  // 12: oelala.storage.v1.SyncService.ListObjects:output_type -> oelala.storage.v1.ListObjectsResponse
	8,  // 13: oelala.storage.v1.SyncService.GetObject:output_type -> oelala.storage.v1.ObjectChunk
	9,  // 14: oelala.storage.v1.SyncService.PushObject:output_type -> oelala.storage.v1.PushObjectResponse
	11, // 15: oelala.storage.v1.SyncService.SyncStatus:output_type -> oelala.storage.v1.SyncStatusResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_storage_proto_init() }
func file_api_proto_storage_proto_init() {
	if File_api_proto_storage_proto != nil {
		return
	}
	file_api_proto_storage_proto_msgTypes[7].OneofWrappers = []any{
		(*ObjectChunk_Meta)(nil),
		(*ObjectChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_storage_proto_rawDesc), len(file_api_proto_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_storage_proto_goTypes,
		DependencyIndexes: file_api_proto_storage_proto_depIdxs,
		EnumInfos:         file_api_proto_storage_proto_enumTypes,
		MessageInfos:      file_api_proto_storage_proto_msgTypes,
	}.Build()
	File_api_proto_storage_proto = out.File
	file_api_proto_storage_proto_goTypes = nil
	file_api_proto_storage_proto_depIdxs = nil
}
